"""Curated general-projection and missing-mask API for the private beta."""

from ._impl.fit_control import FitMode, FitStatus
from ._impl.general_fit_control import (
    GroupedGeneralFitResult,
    fit_converged_grouped,
    fit_fixed_steps_grouped,
)
from ._impl.general_grouped import (
    GroupedPosteriorResult,
    posterior_components_grouped,
)
from ._impl.general_inference import (
    log_likelihood_general,
    log_likelihood_grouped,
    posterior_general,
    posterior_grouped,
    posterior_mean_general,
    posterior_mean_grouped,
    predict_general,
    predict_grouped,
    predict_proba_general,
    predict_proba_grouped,
    score_general,
    score_grouped,
    score_samples_general,
    score_samples_grouped,
)
from ._impl.general_sampling import (
    ValidatedGeneralSamplingInputs,
    canonicalize_general_sampling_inputs,
    sample_observed_general,
    sample_observed_general_from_specs,
)
from ._impl.general_validation import (
    GeneralMaskGroup,
    GroupedGeneralFitInputs,
    GroupedGeneralInputs,
    IdentityProjection,
    NoInformativeWeightError,
    PerItemDiagonalNoise,
    PerItemFullNoise,
    PerItemIsotropicNoise,
    PerItemProjection,
    SharedDiagonalNoise,
    SharedFullNoise,
    SharedIsotropicNoise,
    SharedProjection,
    ValidatedGeneralFitInputs,
    ValidatedGeneralInputs,
    ValidationError,
    PrecisionError,
    canonicalize_general_fit_inputs,
    canonicalize_general_inference_inputs,
    group_masked_general_fit_inputs,
    group_masked_general_inputs,
)
from ._impl.general_xd import posterior_components_general
from ._impl.identity_xd import EStep, Params
from ._impl.metadata import (
    GENERAL_CONTRACT_ID,
    GENERAL_CONTRACT_VERSION,
    GeneralResultMetadata,
)


__all__ = [
    "GENERAL_CONTRACT_ID",
    "GENERAL_CONTRACT_VERSION",
    "EStep",
    "FitMode",
    "FitStatus",
    "GeneralMaskGroup",
    "GeneralResultMetadata",
    "GroupedGeneralFitInputs",
    "GroupedGeneralFitResult",
    "GroupedGeneralInputs",
    "GroupedPosteriorResult",
    "IdentityProjection",
    "NoInformativeWeightError",
    "Params",
    "PerItemDiagonalNoise",
    "PerItemFullNoise",
    "PerItemIsotropicNoise",
    "PerItemProjection",
    "PrecisionError",
    "SharedDiagonalNoise",
    "SharedFullNoise",
    "SharedIsotropicNoise",
    "SharedProjection",
    "ValidatedGeneralFitInputs",
    "ValidatedGeneralInputs",
    "ValidatedGeneralSamplingInputs",
    "ValidationError",
    "canonicalize_general_fit_inputs",
    "canonicalize_general_inference_inputs",
    "canonicalize_general_sampling_inputs",
    "fit_converged_grouped",
    "fit_fixed_steps_grouped",
    "group_masked_general_fit_inputs",
    "group_masked_general_inputs",
    "log_likelihood_general",
    "log_likelihood_grouped",
    "posterior_components_general",
    "posterior_components_grouped",
    "posterior_general",
    "posterior_grouped",
    "posterior_mean_general",
    "posterior_mean_grouped",
    "predict_general",
    "predict_grouped",
    "predict_proba_general",
    "predict_proba_grouped",
    "sample_observed_general",
    "sample_observed_general_from_specs",
    "score_general",
    "score_grouped",
    "score_samples_general",
    "score_samples_grouped",
]
